name: Datamosh Video and Create Release

on:
  push:
    paths:
      - 'videos/*.mp4'
      - 'videos/*.mov'
  workflow_dispatch:
    inputs:
      video_file_path:
        description: '処理するローカル動画ファイルへのパス (例: videos/input.mp4)'
        required: false # ニコニコ動画URLが指定された場合は不要
        default: ''
      niconico_video_url:
        description: 'データモッシュするニコニコ動画のURL (例: https://www.nicovideo.jp/watch/smXXXXXX)'
        required: false # ローカルファイルパスが指定された場合は不要
        default: ''
      glitch_count:
        description: 'グリッチの回数'
        required: false
        default: '15'
      glitch_strength:
        description: 'グリッチの強度 (バイト数)'
        required: false
        default: '10000'

permissions: # ワークフロー全体の権限を設定
  contents: write # リリース作成とアセットアップロードのために必要
  # pull-requests: write # 必要であればプルリクエストの権限も追加

jobs:
  datamosh:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install FFmpeg and yt-dlp
      run: |
        sudo apt-get update
        sudo apt-get install -y ffmpeg
        sudo apt-get install -y python3-pip # pipをインストール
        pip install yt-dlp # yt-dlpをインストール

    - name: Get changed video files (for push event)
      id: changed-videos
      if: github.event_name == 'push' # pushイベントの場合のみ実行
      uses: tj-actions/changed-files@v40
      with:
        files: |
          videos/*.mp4
          videos/*.mov

    - name: Set input variables for processing
      id: set-inputs
      run: |
        INPUT_FILE="${{ github.event.inputs.video_file_path }}"
        NICONICO_URL="${{ github.event.inputs.niconico_video_url }}"
        GLITCH_COUNT="${{ github.event.inputs.glitch_count || '15' }}"
        GLITCH_STRENGTH="${{ github.event.inputs.glitch_strength || '10000' }}"

        echo "input_file=$INPUT_FILE" >> $GITHUB_OUTPUT
        echo "niconico_url=$NICONICO_URL" >> $GITHUB_OUTPUT
        echo "glitch_count=$GLITCH_COUNT" >> $GITHUB_OUTPUT
        echo "glitch_strength=$GLITCH_STRENGTH" >> $GITHUB_OUTPUT

    - name: Run datamoshing (Push event)
      if: github.event_name == 'push' && steps.changed-videos.outputs.any_changed == 'true'
      run: |
        echo "Found changed video files: ${{ steps.changed-videos.outputs.changed_files }}"
        for file in ${{ steps.changed-videos.outputs.changed_files }}; do
          echo "Processing $file..."
          INPUT_DIR=$(dirname "$file")
          INPUT_FILENAME=$(basename "$file")
          FILENAME_NO_EXT="${INPUT_FILENAME%.*}"
          OUTPUT_FILENAME="${FILENAME_NO_EXT}_datamoshed.mp4"
          OUTPUT_PATH="${INPUT_DIR}/${OUTPUT_FILENAME}"

          # データモッシングスクリプトを実行
          python datamosh.py "$file" "$OUTPUT_PATH" "${{ steps.set-inputs.outputs.glitch_count }}" "${{ steps.set-inputs.outputs.glitch_strength }}"
          
          if [ -f "$OUTPUT_PATH" ]; then
            echo "Successfully created $OUTPUT_PATH"
          else
            echo "Failed to create $OUTPUT_PATH"
            exit 1
          fi
        done

    - name: Run datamoshing (Manual workflow_dispatch)
      id: run-manual-datamosh
      if: github.event_name == 'workflow_dispatch'
      run: |
        INPUT_FILE="${{ steps.set-inputs.outputs.input_file }}"
        NICONICO_URL="${{ steps.set-inputs.outputs.niconico_url }}"
        GLITCH_COUNT="${{ steps.set-inputs.outputs.glitch_count }}"
        GLITCH_STRENGTH="${{ steps.set-inputs.outputs.glitch_strength }}"
        
        PROCESSED_INPUT_FILE="" # 実際にデータモッシュに渡されるファイルパス

        if [[ -n "$NICONICO_URL" ]]; then
          echo "ニコニコ動画URLを処理中: $NICONICO_URL"
          # yt-dlpを使ってダウンロード
          DOWNLOAD_DIR="downloaded_videos"
          mkdir -p "$DOWNLOAD_DIR"
          # Pythonスクリプトのdownload_niconico_video関数を直接呼び出す
          DOWNLOADED_PATH=$(python -c "import datamosh; print(datamosh.download_niconico_video('$NICONICO_URL', '$DOWNLOAD_DIR'))")
          
          if [[ -z "$DOWNLOADED_PATH" || ! -f "$DOWNLOADED_PATH" ]]; then
            echo "エラー: ニコニコ動画のダウンロードに失敗しました。"
            exit 1
          fi
          PROCESSED_INPUT_FILE="$DOWNLOADED_PATH"
          echo "ダウンロードされたファイル: $PROCESSED_INPUT_FILE"
          
          # ダウンロードされたファイルのパスから出力ファイル名を決定
          INPUT_FILENAME=$(basename "$PROCESSED_INPUT_FILE")
          FILENAME_NO_EXT="${INPUT_FILENAME%.*}"
          OUTPUT_FILENAME="${FILENAME_NO_EXT}_datamoshed.mp4"
          OUTPUT_PATH="${DOWNLOAD_DIR}/${OUTPUT_FILENAME}" # ダウンロードディレクトリに出力
        elif [[ -n "$INPUT_FILE" ]]; then
          echo "ローカルファイルパスを処理中: $INPUT_FILE"
          if [[ ! -f "$INPUT_FILE" ]]; then
            echo "エラー: 指定されたファイル '$INPUT_FILE' が見つかりません。"
            exit 1
          fi
          PROCESSED_INPUT_FILE="$INPUT_FILE"
          INPUT_DIR=$(dirname "$INPUT_FILE")
          INPUT_FILENAME=$(basename "$INPUT_FILE")
          FILENAME_NO_EXT="${INPUT_FILENAME%.*}"
          OUTPUT_FILENAME="${FILENAME_NO_EXT}_datamoshed.mp4"
          OUTPUT_PATH="${INPUT_DIR}/${OUTPUT_FILENAME}"
        else
          echo "エラー: 'video_file_path' または 'niconico_video_url' のいずれかを指定してください。"
          exit 1
        fi

        echo "Processing $PROCESSED_INPUT_FILE..."
        echo "Output will be saved to $OUTPUT_PATH"
        echo "Glitch Count: $GLITCH_COUNT"
        echo "Glitch Strength: $GLITCH_STRENGTH"

        python datamosh.py "$PROCESSED_INPUT_FILE" "$OUTPUT_PATH" "$GLITCH_COUNT" "$GLITCH_STRENGTH"

        if [ -f "$OUTPUT_PATH" ]; then
          echo "Successfully created $OUTPUT_PATH"
          echo "output_path=$OUTPUT_PATH" >> $GITHUB_OUTPUT # 次のステップで利用するため出力
          echo "output_filename=$OUTPUT_FILENAME" >> $GITHUB_OUTPUT
          echo "downloaded_file_to_clean=$PROCESSED_INPUT_FILE" >> $GITHUB_OUTPUT # ダウンロードしたファイルをクリーンアップするために出力
        else
          echo "Failed to create $OUTPUT_PATH"
          exit 1
        fi

    - name: Clean up downloaded file (Manual workflow_dispatch)
      if: github.event_name == 'workflow_dispatch' && steps.run-manual-datamosh.outputs.downloaded_file_to_clean != ''
      run: |
        DOWNLOADED_FILE="${{ steps.run-manual-datamosh.outputs.downloaded_file_to_clean }}"
        if [ -f "$DOWNLOADED_FILE" ]; then
          rm "$DOWNLOADED_FILE"
          echo "ダウンロードされた一時ファイル $DOWNLOADED_FILE を削除しました。"
        fi

    - name: Create Release and Upload Asset
      if: (github.event_name == 'push' && steps.changed-videos.outputs.any_changed == 'true') || (github.event_name == 'workflow_dispatch' && success())
      id: create_release_and_upload
      uses: softprops/action-gh-release@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: datamoshed-videos-${{ github.run_number }} # ユニークなタグを生成
        name: Datamoshed Videos ${{ github.run_number }} # リリース名
        body: |
          自動生成されたデータモッシュ動画。
          
          **トリガーイベント:** ${{ github.event_name }}
          **処理されたファイル:** ${{ github.event_name == 'workflow_dispatch' && steps.run-manual-datamosh.outputs.output_filename || '' }}
          ${{ github.event_name == 'push' && steps.changed-videos.outputs.changed_files || '' }}

        draft: false # ドラフトリリースではない
        prerelease: false # プレリリースではない
        files: |
          # pushイベントの場合、videos/ディレクトリ内の_datamoshed.mp4ファイルをすべてアップロード
          ${{ github.event_name == 'push' && 'videos/*_datamoshed.mp4' || '' }}
          # workflow_dispatchの場合、特定の出力ファイルのみをアップロード
          ${{ github.event_name == 'workflow_dispatch' && steps.run-manual-datamosh.outputs.output_path || '' }}

